name: notary_yoga
description: "A Basic Flutter Assignment for Notary Flutter Development Internship"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.11.0
  connectivity_plus: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.16

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    image: assets/images/logo.png
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

